### ISSUE TITLE
Message notifications

### ISSUE THREAD

**Issue by abranson** [accumulator/Quickddit#1]
The app doesn't currently tell you when someone's sent you a PM or replied to one of your comments: when you would see the 'orangered' envelope on the Reddit website. Can I request that this gets implemented as a notification? The messaging page is not simple to get to  - you have to select 'more' from the main pulley menu, then select 'Messages' - but unread messages really the only important part of that, so that's fine if a notification jumped straight to unread messages.

**Comment by accumulator** [comment]
Yes this is nice to have, I've updated the README to include this functionality on the TODO list.

d7cb390e993270cffb8bb81cebcc123e6ea70cbb

**Comment by accumulator** [comment]
implemented in v0.8.0

**Comment by abranson** [comment]
Thanks, this is really nicely done.

**Comment by accumulator** [comment]
Thank you. There's still some improvements to be made, but a more-or-less working solution has been waiting in my local git for a while now, so I wanted to get it finalized and out there.

This also marks the beginning of a harbour and a non-harbour version, as harbour doesn't allow the notification specification to be packaged. This means the harbour version will still show the notifications, but they'll make no sound.

**Comment by abranson** [comment]
They're about to change that I think:

https://github.com/sailfish-sdk/sdk-harbour-rpmvalidator/issues/76

**Comment by accumulator** [comment]
ah that's great! thanks!
