### ISSUE TITLE
.gifv links to .gif for Harmattan?

### ISSUE THREAD

**Issue by nyakze** [accumulator/Quickddit#10]
I'm not sure if that is the case for Jolla, hence only offering only for Harmattan. Quickddit is incapable of opening .gifv so you have to open link in browser, then click the image again so it opens in a video player. 

If you would parse all .gifv as .gif they could be opened inside Quickddit without the need to use external apps. The most common subreddit that comes to mind which has lots of .gifv is /r/aww, but they are pretty much everywhere.

**Comment by nyakze** [comment]
I don't know if you still fancy working on it, but I would also like to suggest a conversion for gfycat links to giant.gfycat that has .gif instead of .gifv so it could be displayed on N9.

**Comment by accumulator** [comment]
I'm hesitant to implement this, because the .gif variants are huuge. Even the thumbs variant is still 21MB (!)
So unless there's a video format that the N9 supports and/or reasonably sized I'm closing this issue.

Feel free to reopen if you think there's a solution to this.

**Comment by nyakze** [comment]
Add is as an option maybe?
