### ISSUE TITLE
Strikeout text not rendered correctly

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#11]
Wonder if it is Silica bug and should be reported there, but strikeout (strikethrough?) text is rendered as normal (or maybe it is good instead of having it not rendered at all, but thought will report it, not sure if seen silica strikeout, BTW totally GRATZ for fixing the non-rendering high resolution pics, it was awesome!!! Seeing now android users complain about gifv or something not rendering correctly for them and am just like: why not use the superior platform, quickddit is just better than xyz.

**Comment by accumulator** [comment]
Good catch. This is apparently default behaviour of the Silica/QtQuick RichText element, although it seems to support the &lt;s&gt; element: http://doc.qt.io/qt-5/richtext-html-subset.html

Will try to work around this via the CSS support, but I give this a 50% chance of success..
