### ISSUE TITLE
Extended D-Bus interface

### ISSUE THREAD

**Issue by nodevel** [accumulator/Quickddit#19]
If I'm not mistaken, Quickddit currently has a [dbus interface](https://github.com/accumulator/Quickddit/blob/07702bd7f193af743eb31f229d2180893b53b1db/sailfish/dbusapp.cpp) for handling incoming private messages.

Any thoughts on extending it with the capability of opening subreddits and posts through this interface?

I have an idea for an app that would scan running Kodi instance and show Reddit comments for currently playing (Youtube/Vimeo/...) videos (just like [this Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/reddit-on-youtube/?src=api)). I could implement Reddit comments in the app itself, but as Quickddit is already an awesome choice for Reddit access, sending a call through [nemo-qml-plugin-dbus](https://git.merproject.org/mer-core/nemo-qml-plugin-dbus) would be an easier option. As this app is rather niche (for Kodi+Reddit+SailfishOS users), it wouldn't make sense to bloat Quickddit or Kodimote with it itself.

**Comment by accumulator** [comment]
Should be easy to add

**Comment by Thaodan** [comment]
Should it pe bossible to open reddit urls with the app?

**Comment by accumulator** [comment]
Yes.

example:
dbus-send --session --type=method_call --dest=org.quickddit / org.quickddit.view.openURL string:https://www.reddit.com/r/jolla
