### ISSUE TITLE
Allow browsing subreddit from a post (guess this is only for /r/all, maybe for multireddits too, never figured those out)

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#23]
Oftentimes when browsing r/all I end up wanting to jump to the subreddit current post is from, would be cool if subreddits in r/all view were clickable like usernames (or extra pulley option at top)

**Comment by accumulator** [comment]
Until recently navigating to a subreddit collapsed the pagestack. Now that that's fixed it's a good idea to make subreddits clickable from the commentpage.

Multireddits you will have to create first via a browser, only then can you edit them :)
