### ISSUE TITLE
Some kind of a way to preserve a message when RATELIMIT hits

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#24]
Not sure what would be the best way to handle this, move back to comment view only after 'success' reply, or storing it temporarily, does not crash at least :)

**Comment by accumulator** [comment]
Using the dialog it is far from straightforward to fix this properly, and leads to a couple of nasty UI hacks to make it work & look good.

Instead I'm planning to move the new, reply and edit operations inside the comment tree. This makes it similar to the website, has the added advantage of having the context visible when replying, and even allows working on multiple replies at the same time or navigate deeper into the pagestack without losing the text.

The inline-edit branch has some work in this direction for those interested

**Comment by accumulator** [comment]
partially fixed (comments only) with merge of inline-edit branch
ff27f559f16c497fbf705efcb627fc14c90dd517

**Comment by accumulator** [comment]
Reopened, reply to private message is still not handling errors correctly

**Comment by accumulator** [comment]
fixed reply to private message case
