### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by d9h20f** [accumulator/Quickddit#25]
Is it possible to translate Quickddit somewhere? If not, I think it would be a good idea to apply for hosting at [Weblate](https://hosted.weblate.org/).

**Comment by szopin** [comment]
Maybe transifex? There is a native SFOS client for that and works quite well (accessibility helps)

**Comment by d9h02f** [comment]
ping @accumulator

**Comment by accumulator** [comment]
https://www.transifex.com/outright-solutions/quickddit/dashboard/
