### ISSUE TITLE
gfycat broken in latest build

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#26]
nothing happens when you click on the icon or the video icon from within a post

**Comment by accumulator** [comment]
It's actually unrelated to the latest build. 

Somehow quickddit gets the following junk in front of the JSON object

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>

Same request with a regular browser doesn't have this html fragment in front..
