### ISSUE TITLE
UI scaling issue (jolla C)

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#27]
The buttons get moved too much to the left on some posts, upvote ends up being halfway outside of screen: http://i.imgur.com/DzNW6Vx.png

**Comment by accumulator** [comment]
Thanks, I've seen this a few times too. I have no idea what causes it yet, as "it should never happen" :)

**Comment by accumulator** [comment]
Cannot reproduce at the moment since the thumbnail is gone on that post. If you encounter another one, please post its URL!
