### ISSUE TITLE
Apostrophes missing in overview

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#29]
Any comment containing apostrophe is displayed without in overview page

**Comment by accumulator** [comment]
do you have a link?

**Comment by szopin** [comment]
can't link to my page, just make a comment with it, can't don't wouldn't won't, if you commented with that word in overview it will be cant dont...

**Comment by accumulator** [comment]
Ok, I see what you mean. I guess it has to do with the new compact rendering of text introduced in 1.4.1. Thanks, good catch, I'll take a look.
