### ISSUE TITLE
Hide subreddits from All

### ISSUE THREAD

**Issue by d9h02f** [accumulator/Quickddit#31]
Would be great if you could add a feature to block specific subreddits from appearing when you're looking at all. There's always a bunch of low quality content you just never want to see.

A comma-separated list in settings would do fine because this is something you only enter once and forget about it.

**Comment by d9h02f** [comment]
Many thanks!

**Comment by d9h02f** [comment]
Looks like this functionality isn't exposed anywhere yet.

**Comment by accumulator** [comment]
It is. just add a 'filteredSubreddits' config line to harbour-quickddit.conf, for example

```
[General]
filteredSubreddits=worldnews,funny

```

**Comment by d9h02f** [comment]
Oh, I see, thanks. Maybe that's a bit too obscure.
