### ISSUE TITLE
Drop support for Harmattan

### ISSUE THREAD

**Issue by dicksonleong** [accumulator/Quickddit#4]
What you think about dropping support for Harmattan? The benefits we can see are:
- No need back porting changes to Harmattan (particulally QML changes)
- Can use new features in Qt5 and C++11, and drop Qt-Json
- Easier to maintain the whole project

Unless you got a valid reason (like they are still huge amount of Harmattan Quickddit users out there), I don't see any advantages on continue maintaining the Harmattan port.

**Comment by accumulator** [comment]
I think it is inevitable at some point.

Already some UI sugar like the internal video player is a sailfish-only feature. Porting this to harmattan is not on my radar. However, for now all changes I made relating to *basic use* of reddit have been quite easy to port. As long as that's the case I see no real reason to not get the harmattan port to the 1.0 milestone.

From openrepos.net/warehouse, which is basically the only distribution platform left for harmattan I can see ~60 downloads of 0.5.0. So yes, it's not a huge crowd, but still significant enough to put in some minor extra effort. I'm doing this stuff for fun, not for my income :)

Dropping Qt-Json or using Qt5/C++11 features is not beneficial enough right now to warrant giving it a higher priority than getting the 1.0 milestone features in. Reducing technical debt is nice, but it's work that doesn't directly lead to new features, which IMO should be the priority for a mobile application on a niche OS with such a small developer base.

**Comment by accumulator** [comment]
Quickddit Harmattan is now at 1.0.0.

It is unlikely new features will be added in the future.
