### ISSUE TITLE
Broken Gfycat links

### ISSUE THREAD

**Issue by Parnassius** [accumulator/Quickddit#46]
Since a few days ago Gfycat links fail to load, with the warning 'Problem finding stream URL'. Apparently the json endpoint used by youtube-dl is gone, and [a fix was commited the youtube-dl repo on November 29](https://github.com/rg3/youtube-dl/commit/16597c2f9492651c55e01f441ee9cb5c276209cb). Upgrading to the latest youtube-dl version should fix this issue.

**Comment by accumulator** [comment]
Thanks for reporting! Youtube-dl update indeed fixes the issue.
