### ISSUE TITLE
Youtube video: Token parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by omartijn** [accumulator/Quickddit#48]
Since the last 2/3 days youtube videos don't work anymore. It seems a new version of youtube-dl is needed.

Also: I wouldn't mind trying to build it myself, but I don't see any kind of Makefile or CMakeLists.txt anywhere. Is that even possible without installing weird things like QtCreator?

**Comment by omartijn** [comment]
Got it to build using a Dockerfile which had all the necessities installed. Needed a small fix as well. Please see the references PR.

**Comment by accumulator** [comment]
Thanks for reporting.
I noticed this as well a few days ago so I already had this change locally, but thanks for the PR anyway!

The project is buildable without any configuration needed by using the SDK. Why would you not use that?

**Comment by omartijn** [comment]
> The project is buildable without any configuration needed by using the SDK. Why would you not use that?

I dislike the SDK - and any kind of integrated build environment like it - because it hides complexity and makes it harder to make things like automated builds. I always like it when everything works from the command-line, makes it easier to set up automated pipelines.

**Comment by accumulator** [comment]
If you can get the dual-variant builds running with Docker, I'm interested! Are you using a custom Dockerfile or are you using some upstream image?

**Comment by omartijn** [comment]
I used the Dockerfile from https://github.com/CODeRUS/docker-sailfishos-sdk to create a build container. In the container the required `specify` and `mb2` commands are available.

Like I said, doing the `specify` and `mb2` for the harbour yaml didn't work, so there would be an additional step to add harbour to CONFIG in the .pro file.

Are you looking at setting up a build pipeline?

**Comment by accumulator** [comment]
Not really a whole build pipeline, but as I am not actively working on Quickddit at the moment it's more convenient to have a docker image to do the build quickly from a script, instead of having to involve virtualbox in this process. It would also make it easier to revert to an older SDK release (though that would probably not be needed for Quickddit).
