### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by mitchcurtis** [accumulator/Quickddit#50]
Is an Android client out of the question? Would you accept patches?

**Comment by accumulator** [comment]
It's not out of the question, but this would mean a MAJOR rewrite of the UI, adding an abstract intermediate layer on top of Silica (and prob kirigami for Android). It's not just an issue of accepting patches, you'd also have to commit to (help) maintaining the code :)

Do you think there's room for yet another reddit client in the android space?

**Comment by mitchcurtis** [comment]
>Do you think there's room for yet another reddit client in the android space?

The Joey client just put ads in after being free for ages. That was the best free client for Android that I've found so far. So, yes, I really do. :)

>It's not out of the question, but this would mean a MAJOR rewrite of the UI, adding an abstract intermediate layer on top of Silica (and prob kirigami for Android). It's not just an issue of accepting patches, you'd also have to commit to (help) maintaining the code :)

I see... perhaps I will fork it and play around a little with writing a UI from scratch. I can't commit to anything as I have my own ongoing projects, that's why I thought I'd just throw the idea out there first. :)

**Comment by accumulator** [comment]
Have a look at https://github.com/rinigus/pure-maps
Rinigus already did some of this platform-abstraction work (and that was in turn based on some other work, for which I don't have the link right now)

**Comment by null-von-sushi** [comment]
> The Joey client just put ads in after being free for ages. That was the best free client for Android that I've found so far. So, yes, I really do. :)

Just wanted to mention, Android has RedReader already which works rather well. [It's on F-Droid.](https://f-droid.org/en/packages/org.quantumbadger.redreader/)

**Comment by mitchcurtis** [comment]
> > The Joey client just put ads in after being free for ages. That was the best free client for Android that I've found so far. So, yes, I really do. :)
> 
> Just wanted to mention, Android has RedReader already which works rather well. [It's on F-Droid.](https://f-droid.org/en/packages/org.quantumbadger.redreader/)

Thanks, going to try that out.
