### ISSUE TITLE
Make behavior consistent 

### ISSUE THREAD

**Issue by null-von-sushi** [accumulator/Quickddit#51]
In SFOS (or any mobile os really) tap and hold brings up a menu of sorts, while tapping performs an action. Please add an option to reverse the current behaviour when it comes to hiding comments/showing the option bar (where you can upvote) as it's extremely unnatural .

**Comment by accumulator** [comment]
I agree it's inconsistent. It kinda grew this way, and I think most users have gotten used to the way it works now. I'll look into adding a config option.

I guess the only place where this is an issue is the comment hiding vs. comment menu popup? If not, please add any other places where this pops up (pun intended).

**Comment by null-von-sushi** [comment]
Heh. Yeah it's only the comment hiding / upvoting where I've seen it. 
Thanks for looking into it :)
