### ISSUE TITLE
Posting links doesn't work

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#54]
Only selfposts allow submitting

**Comment by szopin** [comment]
Not sure why this got closed, mobile view issue maybe

**Comment by accumulator** [comment]
Thanks for noticing this! It's a regression that appears on subreddits that have no flairs. 

Your patch however could be even shorter. The check for subredditsFlair.length should I think be totally removed (unless I'm missing something?), and the check for linkTitle.text.length is already satisfied one line above.

Could you change the line to

`&& ((selfLinkSwitch.checked && linkDescription.text.length > 0) || (!selfLinkSwitch.checked && linkUrl.acceptableInput))
`

**Comment by szopin** [comment]
Updated, didn't want to touch the flair part as still never seen this feature in action, so no idea how that works, for normal subreddits checked and the submit button does light up now as expected, thanks!

**Comment by accumulator** [comment]
Merged, thanks.

Flair is a bit complex, there are subreddits that allow you to choose from a list (which is implemented in Quickddit) and there are subreddits where you can enter custom flair text (not implemented). The flair part in the button enable check was to allow choosing a new flair and submit, but that broke the button for subreddits without a flair list. So, corner case but good find!
