### ISSUE TITLE
Only http(s) links can be posted

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#56]
Bit niche issue but current link validator doesn't allow ftp links for example: https://www.reddit.com/r/opendirectories/comments/dl3caj/ancient_ibm_stuff/ this will not pass quickddit checks

**Comment by accumulator** [comment]
Very niche.. Maybe too niche to be worth the effort :)

Or are there other links/protocols that are allowed to be posted?
(e.g. like bitcoin:xyz)

**Comment by szopin** [comment]
Yeah, probably too niche (there's probably more like dht/magnet, gopher maybe?), in any case unless a subreddit would require submissions in only the url can always post them in self posts anyway
