### ISSUE TITLE
[feature request] incorporate revddit/removeddit/ceddit 

### ISSUE THREAD

**Issue by szopin** [accumulator/Quickddit#58]
I don't believe any android or else client has it, but it would be awesome to be able to see deleted comments from within the app, seems to be more and more needed feature though

**Comment by szopin** [comment]
So it looks lile there is an api that could be used to pull individual comments (https://pushshift.io/api-parameters/) but not sure if it's the way to go, sometimes dozens (even hundreds) comments get nuked, so clicking them one by one would just be a nightmare. Maybe adding a similar 'Uncensor' to pulldown menu could work if body of submission is [deleted]/[removed]? (this also avoids having to have an icon for this, which no idea how it could look like)

**Comment by szopin** [comment]
A more useful link about pushshift api: https://github.com/pushshift/api

**Comment by accumulator** [comment]
Yeah this would be great to have implemented. It's already in the TODO list in the README for years, but very hard to neatly get into the UI..
