### ISSUE TITLE
App is not remmembering default login

### ISSUE THREAD

**Issue by dano6** [accumulator/Quickddit#67]
Steps to reproduce:
- Login to Quickddit
- Exit Quickddit 
- Turn off network
- Open Quickddit
- Close Quickddit
- Turn on network
- Open Quickddit
- You are not logged in (you need to select account in settings again)
This bug is present in both Sailfish OS and Ubuntu-touch version

**Comment by accumulator** [comment]
Thanks for the steps to reproduce. I've seen this only a few times, apparently I have a stable network :)
