### ISSUE TITLE
Cannot add an account on Ubuntu Touch.

### ISSUE THREAD

**Issue by Hacker1245** [accumulator/Quickddit#69]
When I log in from the app this happens:
![screenshot20200706_145520494](https://user-images.githubusercontent.com/29224894/86595668-58dcfa80-bf99-11ea-916f-9b56cb4cd870.png)
Translates to invalid request.

**Comment by dano6** [comment]
Did you get api access as writen in README ? For login support you need to define varables as explained in README file.

**Comment by Hacker1245** [comment]
What should I put in the redirect URL on the app id creation page?

**Comment by dano6** [comment]
That is not important (we are not using it), any url should work, but it must be defined

**Comment by Hacker1245** [comment]
works now

**Comment by dano6** [comment]
Great!
