### ISSUE TITLE
Merge 'Copy Comment' and 'Permalink' into one 'Share' option

### ISSUE THREAD

**Issue by nodevel** [accumulator/Quickddit#7]
Seeing so many (6!) options in the comment context menu, I have got an idea that would both reduce the number of icons and also make it easier to understand for a regular user.

I would replace *Copy Comment* and *Permalink* with a *Share* option. It would open the current Permalink dialog, but also feature a 'Copy Comment' button there.

I believe that 'Permalink' is quite a cryptic term for a regular user, so sharing option would be more understandable and this move would also bring the advantage of having a dedicated sharing page that could be expanded later.

PS: I might implement it myself, but I don't have much time right now (which resulted in the pull request fiasco the last time).

**Comment by accumulator** [comment]
Sorry, I don't think this will happen in the form described here.
