### ISSUE TITLE
Crash during parsing reddit gallery

### ISSUE THREAD

**Issue by dano6** [accumulator/Quickddit#77]
I am getting crash during opening https://www.reddit.com/r/i3wm/comments/istk9z/just_upgraded_my_system_and_my_i3blocks_volume/
@accumulator can you please test with Sailfish version?
crash log:

```
ASSERT failure in QList<T>::at: "index out of range"
```

**Comment by dano6** [comment]
This gallery is weird because second image doesn't have preview, other two have.

**Comment by accumulator** [comment]
confirmed
