### ISSUE TITLE
[UBPorts] Issue with multi-account.  

### ISSUE THREAD

**Issue by Count042** [accumulator/Quickddit#78]
The list of accounts only shows the first account I initially signed in with.   If I try to add an additional account, it shows the 'connect quickddit to account' page, and won't let me login to the second account.

If I logout of the initial account and try to add the second account, I can, but the list of accounts only shows the first, initial account.

**Comment by dano6** [comment]
Can you please test now with updated version from the OpenStore?

**Comment by dano6** [comment]
V  1.0.1 should fix this. If not, please remove ~/.config/quickddit.conf file or clean config with UT Tweak Tool

**Comment by Count042** [comment]
You updated it before I finished testing it out on V1.0.0, and saw that it was broken. :)  V 1.0.1 does work, and quite well.   Thank you so much!
