### ISSUE TITLE
Facebook image links

### ISSUE THREAD

**Issue by nyakze** [accumulator/Quickddit#8]
For some reason Quickddit is adding amp; to facebook image urls (*.fbcdn.net). Preview is working fine but if you try to open or copy it, you won't be able to.
Example of links:
Correct one: (NSFW)
https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/984265_628802043920534_7984640431054628742_n.jpg?oh=aeb98c2e935bd2f86a690d9434f51f40&oe=56CD84CD

The one you get in Quickddit:
https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/984265_628802043920534_7984640431054628742_n.jpg?oh=aeb98c2e935bd2f86a690d9434f51f40&amp;oe=56CD84CD

Note that I'm using Harmattan version, it's possible that it's working fine on Sailfish.

**Comment by accumulator** [comment]
lovely bugreport, thanks :]

in which subreddit can I find these links?

**Comment by nyakze** [comment]
/r/cosplaygirls for one ^^
