### ISSUE TITLE
v1.2 unusable on Xperia X UBPorts 

### ISSUE THREAD

**Issue by VenKamikaze** [accumulator/Quickddit#85]
Hi,

I'm unable to load a majority of the comment threads since updating to v1.2. On rare occasion one might open after waiting for some time after selecting it.

The user menu also seem to behave almost as if lagged. E.g. I'll open it fine, but on selecting an action it won't finish the fade out in a timely manner but still appears semi-transparent for perhaps 10 seconds or so.

v.1.1 worked fairly well for me before.

I've tried re-compiling 1.1 from git but am having issues.

Would you be so kind as to point me to a download of the previous v1.1 arm64 clickable package somewhere?

Cheers

**Comment by dano6** [comment]
Can you please test with a new release? Old releases can be somehow downloaded using open-store API https://open-store.io/api/v3/apps/quickddit/

**Comment by VenKamikaze** [comment]
Thanks for both the fix and the API link listing releases.

I've done a very quick test of 1.3 on my device and so far its working well.

Thanks again!
