### ISSUE TITLE
Quickddit forgetting settings

### ISSUE THREAD

**Issue by peperjohnny** [accumulator/Quickddit#95]
I installed version 1.11.0 and have the problem that I'm no longer logged in and my settings are gone. I can log in and set the settings and it works until I reopen the app.
However, if I start the app via terminal or ssh it works fine and is logged in and has the settings set.

Start via GUI. Log has been taking with journalctl -f over ssh

`invoker[12140]: warning: enforcing sandboxing for '/usr/bin/harbour-quickddit'
lipstick[5322]: Error: can't chdir to privileged
lipstick[5322]: constructing /run/firejail/mnt/privileged: Images ...
lipstick[5322]: mounting /run/firejail/mnt/privileged @ /home/defaultuser/.local/share/system/privileged
lipstick[5322]: hiding /run/firejail/mnt/privileged
lipstick[5322]: Error: can't chdir to privileged
harbour-quickddit[12186]: [D] unknown:0 - Using Wayland-EGL
lipstick[5322]: library "libGLESv2_adreno.so" not found
lipstick[5322]: library "eglSubDriverAndroid.so" not found
mce[1637]: modules/proximity.c: mp_datapipe_set_proximity_sensor_actual(): state: OPEN -> UNDEF
harbour-quickddit[12186]: [D] unknown:0 - Device PPI = 458.845 scale = 2 rpw = 1.05482
harbour-quickddit[12186]: [D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
harbour-quickddit[12186]: [W] unknown:0 - Could not open "/usr/share/sailfish-browser/data/ua-update.json.in"
harbour-quickddit[12186]: [W] unknown:0 - "/home/defaultuser/.cache/nl.outrightsolutions/Quickddit/.mozilla/ua-update.json" parse error "illegal value" at offset 0
harbour-quickddit[12186]: [D] unknown:0 - requesting "/hot"
harbour-quickddit[12186]: [W] unknown:153 - file:///usr/share/harbour-quickddit/qml/main.qml:153: TypeError: Cannot read property 'path' of null
invoker[5816]: WARNING: An inactive plugin is misbehaving - tried to show a window!
invoker[5816]: WARNING: requestActivate() called for  QQuickView(0x25052fd0)  which has Qt::WindowDoesNotAcceptFocus set.
lipstick[5322]: [W] unknown:0 - WindowPixmapItem does not have a source texture, cover will be dropped..
harbour-quickddit[12186]: [D] unknown:0 -
harbour-quickddit[12186]: [D] unknown:0 - got 50 items
lipstick[5322]: greHome from GRE_HOME:/usr/bin
lipstick[5322]: libxul.so is not found, in /usr/bin/libxul.so
lipstick[5322]: Created LOG for EmbedLiteTrace
lipstick[5322]: Created LOG for EmbedLite
lipstick[5322]: Created LOG for EmbedPrefs
booster-generic[5161]: *** signal=17 pid=5161
/usr/libexec/mapplauncherd/booster-generic[5161]: warning: Daemon: sending exit(0) to invoker(12140)`

Start via terminal
`[D] unknown:0 - Using Wayland-EGL
library "libGLESv2_adreno.so" not found
library "eglSubDriverAndroid.so" not found
[D] unknown:0 - Device PPI = 458.845 scale = 2 rpw = 1.05482
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
greHome from GRE_HOME:/usr/bin
libxul.so is not found, in /usr/bin/libxul.so
Created LOG for EmbedLiteTrace
[D] unknown:0 - requesting "/hot"
Created LOG for EmbedLite
[W] unknown:153 - file:///usr/share/harbour-quickddit/qml/main.qml:153: TypeError: Cannot read property 'path' of null
Created LOG for EmbedPrefs
[D] unknown:0 - saveRefreshToken "50240389-fxmIe0qTWDzsbKpS_95PRbROyC58lA" "peperjay"
[D] unknown:0 - Reddit Rate Limit: Remaining: 599.0, Reset: 510s
[D] unknown:0 - got 50 items
[D] unknown:0 - 
`

First I thought it was sailjail and turned it off via 
`Sandboxing=Disabled`
in the desktop file, but this changed nothing.

**Comment by vigejolla** [comment]
I'm quite sure that's because the commits 061c02f and 9da1be8 changed the assumed location of the settings files. However, the Settings constructor seems to use the default constructor, which unfortunately uses a wrong location for the configuration file.  https://forum.sailfishos.org/t/migrating-configuration-and-data-files-for-sandboxed-apps/8866 provides some hints how to fix the code, even migrating the configuration from the old place to the new.

**Comment by DeathByDenim** [comment]
I was tinkering a bit with this today and it seems to be a bit more complicated than that. I compiled this repo and installed it on my phone. When I use this in src/settings.cpp, it work when using SailJail:
```
    const QString settingsPath =
            QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) +
            "/harbour-quickddit/Quickddit.conf";
    m_settings = new QSettings(settingsPath, QSettings::NativeFormat, this);
```
Of course, that is just enforcing the old config locations.

I also tried the new one, but SailJail does not seem to allow reading/writing to "/home/defaultuser/.config/nl.outrightsolutions/Quickddit/Quickddit.conf" as the forum link and https://github.com/sailfishos/sailjail-permissions claim. This is what I tried:
```
    const QString settingsPath =
        QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation)
        + "/" + QCoreApplication::applicationName() + ".conf";
```
That indeed resolves to /home/defaultuser/.config/nl.outrightsolutions/Quickddit/Quickddit.conf

Anyway, my initial code block would fix this albeit with the old config location.

**Comment by vigejolla** [comment]
> I was tinkering a bit with this today and it seems to be a bit more complicated than that. I compiled this repo and installed it on my phone. When I use this in src/settings.cpp, it work when using SailJail:
> 
> Of course, that is just enforcing the old config locations.

That will work, if the old configuration already exists. If it doesn't, i.e. for new users, it won't work. 

> I also tried the new one, but SailJail does not seem to allow reading/writing to "/home/defaultuser/.config/nl.outrightsolutions/Quickddit/Quickddit.conf" as the forum link and https://github.com/sailfishos/sailjail-permissions claim. This is what I tried:

To me your code indeed seems correct and it should work. Is that version in git somewhere so I could have a closer look?

**Comment by DeathByDenim** [comment]
> > I was tinkering a bit with this today and it seems to be a bit more complicated than that. I compiled this repo and installed it on my phone. When I use this in src/settings.cpp, it work when using SailJail:
> > Of course, that is just enforcing the old config locations.
> 
> That will work, if the old configuration already exists. If it doesn't, i.e. for new users, it won't work.

I did `rm -r harbour-quickddit/ nl.outrightsolutions/` before in the .config directory and it still works. That should emulate a new user as far as I know. I just did that again to make sure.
> 
> > I also tried the new one, but SailJail does not seem to allow reading/writing to "/home/defaultuser/.config/nl.outrightsolutions/Quickddit/Quickddit.conf" as the forum link and https://github.com/sailfishos/sailjail-permissions claim. This is what I tried:
> 
> To me your code indeed seems correct and it should work. Is that version in git somewhere so I could have a closer look?

I don't have it on Git yet since my API keys are still in there and I haven't figured out yet how to keep that external. Should be possible in the project settings somewhere. Anyway, this is the part that I changed:
```
#include <QtCore/QSettings>
#include <QDebug>
#include <QStandardPaths>
#include <QCoreApplication>

Settings::Settings(QObject *parent) :
    QObject(parent)
{
//    const QString settingsPath =
//        QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation)
//        + "/" + QCoreApplication::applicationName() + ".conf";
    const QString settingsPath =
            QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) +
            "/harbour-quickddit/Quickddit.conf";
    m_settings = new QSettings(settingsPath, QSettings::NativeFormat, this);
    qDebug() << "Settings path = " << settingsPath << '\n';
    m_commentsTapToHide = m_settings->value("commentsTapToHide", true).toBool();
    qDebug() << "m_commentsTapToHide = " << m_commentsTapToHide << '\n';
```
That is, I added the includes and I moved the m_settings initialization and changed it.

Weirdly enough, I also had to comment out the DBus stuff in main.cpp otherwise an assertion would fail due to SailJail.
```
//    DbusApp dbusApp;
//    view->rootContext()->setContextProperty("DbusApp", &dbusApp);
```
Anyway, that is a separate issue. I'm surprised the version in the Jolla Store works though.

**Comment by vigejolla** [comment]
Ok, finally I found the issue. Your .desktop file has section `[X-SailJail]` when it should be `[X-Sailjail]`. Note the lower case `j`.

**Comment by DeathByDenim** [comment]
Oh brilliant! So that's in combination with adjusting the settings path, right? That is, this one:
```
    const QString settingsPath =
            QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) +
            "/harbour-quickddit/Quickddit.conf";
```
That seems to work for me.

**Comment by vigejolla** [comment]
> Oh brilliant! So that's in combination with adjusting the settings path, right? That is, this one:

Yes, exactly. And if you wish to automatically migrate the settings for old users, please refer to the forum post. Basically it's just copying the settings file from the old location to the new.
